version: '3'
services:

  staginator_api:
    build: docker_data/staginator_api/
    container_name: staginatorJD_staginator
    ports:
      - ${APPLICATION_PORT}:80
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./staginator_api:/home/node/app"
    command: "npm start"
    depends_on:
      - redis
    env_file: .env
    restart: always

  redis:
    image: redis:3.2-alpine
    container_name: staginatorJD_redis
    volumes:
      - "./redis/data:/data"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"

  staginator_web:
    working_dir: /home/node/app
    env_file: .env
    volumes:
      - "./staginator_web:/home/node/app"
    command: "NODE_ENV=production node_modules/.bin/webpack --progress --config webpack.config.js"

networks:
  staginatorJD_redis: