version: '3'
services:

  staginator_api:
    image: staginator_api_image
    build: docker_data/staginator_api/
    container_name: staginatorJD_api
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    depends_on:
      - redis
    env_file:
      - docker_data/staginator_api/.env
      - docker_data/staginator_api/.env.default
    entrypoint:
      - APPLICATION_PORT=1337
      - NODE_ENV=production
      - APP_URL=http://api.stage
      - BASE_STAGE_HOST=stagings.stage
      - NGINX_CONFIG_FILES_PATH=/etc/nginx/sites_enabled/
      - GITLAB_HOST=http://gitlab.stage
      - GITLAB_APP_ID=71327257d2f2e35ffec19242c63818819b98e7a30c63c907847c40e96208703e
      - GITLAB_SECRET=
    ports:
      - '20050:1337'
    restart: always

  redis:
    image: redis:3.2-alpine
    container_name: staginatorJD_redis
    volumes:
      - "./docker_data/redis/data:/data"
      - "./docker_data/redis/redis.conf:/usr/local/etc/redis/redis.conf"

  staginator_web:
    image: staginator_web_image
    build: docker_data/staginator_web/
    container_name: staginatorJD_web
    env_file:
      - docker_data/staginator_web/.env
      - docker_data/staginator_web/.env.default
    entrypoint:
      - NODE_ENV=production
      - API_URL=http://api.stage
    ports:
     - "20051:80"